CREATE TABLE "User" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "email" varchar UNIQUE,
  "phone" varchar,
  "password" varchar,
  "createdAt" datetime,
  "updatedAt" datetime
);

CREATE TABLE "Address" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "line1" varchar,
  "pincode" varchar,
  "createdAt" datetime,
  "updatedAt" datetime
);

CREATE TABLE "Product" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar,
  "price" decimal,
  "stock" int,
  "image" varchar,
  "createdAt" datetime,
  "updatedAt" datetime
);

CREATE TABLE "cart" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "createdAt" datetime,
  "updatedAt" datetime
);

CREATE TABLE "cart_item" (
  "int" SERIAL PRIMARY KEY,
  "cart_id" int,
  "product_id" int,
  "quantity" int,
  "createdAt" datetime,
  "updatedAt" datetime,
  "deletedAt" datetime
);

CREATE TABLE "order" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "order_address_id" int,
  "createdAt" datetime,
  "updatedAt" datetime
);

CREATE TABLE "order_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int,
  "product_id" int,
  "quantity" int,
  "price" decimal,
  "createdAt" datetime,
  "updatedAt" datetime
);

CREATE TABLE "order_address" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "line1" varchar,
  "line2" varchar,
  "pincode" varchar,
  "order_id" int,
  "createdAt" datetime,
  "updatedAt" datetime
);

ALTER TABLE "cart" ADD FOREIGN KEY ("id") REFERENCES "User" ("id");

ALTER TABLE "Product" ADD FOREIGN KEY ("id") REFERENCES "cart_item" ("int");

ALTER TABLE "order" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "cart_item" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("id");

ALTER TABLE "Address" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "order_address" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "cart_item" ADD FOREIGN KEY ("cart_id") REFERENCES "cart" ("id");

ALTER TABLE "order_address" ADD FOREIGN KEY ("id") REFERENCES "order" ("order_address_id");
